const art = "The history of Cambodian art stretches back centuries to ancient times, but the most famous period is undoubtedly the Khmer art of the Khmer Empire (802–1431), especially in the area around Angkor and the mainly 12th-century temple-complex of Angkor Wat, initially Hindu and subsequently Buddhist. After the collapse of the empire these and other sites were abandoned and overgrown, allowing much of the era's stone carving and architecture to survive to the present day. Traditional Cambodian arts and crafts include textiles, non-textile weaving, silversmithing, stone carving, lacquerware, ceramics, wat murals, and kite-making. Beginning in the mid-20th century, a tradition of modern art began in Cambodia, though in the later 20th century both traditional and modern arts declined for several reasons, including the killing of artists by the Khmer Rouge. The country has experienced a recent artistic revival due to increased support from governments, NGOs, and foreign tourists. In pre-colonial Cambodia, art and crafts were generally produced either by rural non-specialists for practical use or by skilled artists producing works for the Royal Palace. In modern Cambodia, many artistic traditions entered a period of decline or even ceased to be practiced, but the country has experienced a recent artistic revival as the tourist market has increased and governments and NGOs have contributed to the preservation of Cambodian culture.";
const architecture ="Khmer architecture (Khmer: ស្ថាបត្យកម្មខ្មែរ), also known as Angkorian architecture is the architecture produced by the Khmers during the Angkor period of the Khmer Empire from approximately the later half of the 8th century CE to the first half of the 15th century CE. The architecture of the Indian rock-cut temples, particularly the sculptures, were widely adopted in South Indian, and Indianised architecture of Cambodian, Annamese (Khmer) and Javanese temples (of the Greater India). In any study of Angkorian architecture, the emphasis is necessarily on religious architecture, since all the remaining Angkorian buildings are religious in nature. During the period of Angkor, only temples and other religious buildings were constructed of stone. Non-religious buildings such as dwellings were constructed of perishable materials such as wood, and so have not survived. The religious architecture of Angkor has characteristic structures, elements, and motifs, which are identified in the glossary below. Since a number of different architectural styles succeeded one another during the Angkorean period, not all of these features were equally in evidence throughout the period. Indeed, scholars have referred to the presence or absence of such features as one source of evidence for dating the remains.";
const sculpture  ="Khmer sculpture refers to the stone sculpture of the Khmer Empire, which ruled a territory based on modern Cambodia, but rather larger, from the 9th to the 13th century. The most celebrated examples are found in Angkor, which served as the seat of the empire, captivating in its civility, refinement and delight, open to all forms of life, is made in the image of the country and its inhabitants. Nevertheless, among the arts of the Far East, few are as accessible to the Western temperament. Its profound beauty impresses itself upon the spirit and sensibility without requiring prior study. Its sobriety, its horror of excess and its sense of balance and harmony allow it to attain universal value.” Thus wrote Madeleine Giteau, the distinguished member of the École française d’Extrême-Orient, in the introduction to her book Les Khmers in 1965. Currently, the largest museums of the West dedicate entire halls to Khmer sculpture, not to mention the enormous exhibition which took place first at the Galeries Nationales du Grand Palais in Paris and later at the National Gallery of Art in Washington in 1997.";
const destruction ="Because of destruction during recent war, few historic wat murals remain in Cambodia. In the 1960s, art historians Guy and Jacqueline Nafilyan photographed 19th-century murals, providing a record of this lost cultural heritage. The best known surviving murals are at the Silver Pagoda in Phnom Penh, Wat Rajabo in Siem Reap province, and Wat Kompong Tralach Leu in Kompong Chhnang Province. In the last decade, wat murals have seen a resurgence, but Cambodia's surviving older murals are generally more refined and detailed.";
const music ="The music of Cambodia is derived from a mesh of cultural traditions dating back to the ancient Khmer Empire, India, China and the original indigenous tribes living in the area before the arrival of Indian and Chinese travelers. With the rapid Westernization of popular music, Cambodian music has incorporated elements from music around the world through globalization.";
const classical="Cambodian Art music is highly influenced by ancient forms as well as Hindu forms. Religious dancing, many of which depict stories and ancient myths, are common in Cambodian culture. Some dances are accompanied by a pinpeat orchestra, which includes a ching (cymbal), roneat (bamboo xylophone), pai au (flute), sralai (oboe), chapey (bass moon lute or banjo), gong (bronze gong), tro (fiddle), and various kinds of drums. Each movement the dancer makes refers to a specific idea, including abstract concepts like today (pointing a finger upwards). The 1950s saw a revival in classical dance, led by Queen Sisowath Kossamak Nearyrath. During the early 1970s, the Khmer Rouge of Cambodia committed genocide among the country's citizens. During their reign, an estimated (90% of Cambodia's musicians, dancers, teachers, and instrument makers) were killed, interrupting the transmission of cultural knowledge to following generations. The country has been undergoing revival ever since, with those remaining trying to perform, teach, research, and document what they can.";
const rockAndPop="Starting in the late 1950, Head of State Norodom Sihanouk, a musician himself, encouraged the development of popular music in Cambodia. Initially, pop records from France and Latin America were imported into the country and became popular, inspiring a flourishing music scene based in Phnom Penh and led by singers like Ros Serey Sothea, Pen Ran or Sinn Sisamouth, with hits such as 'Violon Sneha'. By the late 1960s and early 1970s, the scene was further influenced by Western rock and roll and soul music via U.S. armed forces radio that had been broadcast into nearby South Vietnam. This resulted in a unique sound in which Western pop and rock were combined with Khmer vocal techniques. Many of the most important singers of this era perished during the Khmer Rouge genocide. Western interest in the popular Cambodian music of the 1960s-70s was sparked by the bootleg album Cambodian Rocks in 1996, which in turn inspired the 2015 documentary film.";
const literatuerOfCambodia="This type of art is a composition to be written as a story so that the reader and listener will not only be impressed but Literary texts Always contain a deep knowledge of the realities of real life, and they also reflect the phenomena that exist in society, especially in accordance with the laws of social progress. Knowledge of life, human issues related to traditions, geography, history and so on.";
const danceInCambodia="Dance in Cambodia (Khmer: របាំ robam) consists of three main categories: classical dance of the royal court, folk dance which portrays cultural traditions, and social dances performed in social gatherings.";
const classicalDance = "Cambodia's premier performing art form is Khmer classical dance, or Robam Preah Reach Trop, a highly stylized dance form originating from the royal courts. Originally performed and maintained by attendants of the royal palaces, Khmer classical dance was introduced to the general public in the mid-20th century and became widely celebrated as iconic of Cambodian culture, often performed during public events, holidays, and for tourists visiting Cambodia. Performances feature elaborately costumed dancers performing slow and figurative gestures to the musical accompaniment of a pinpeat ensemble. The classical repertoire includes dances of tribute or invocation and the enactment of traditional stories and epic poems such as the Ramayana. Two of the most performed classical dances are the Robam Chuon Por ('Wishing dance') and the Robam Tep Apsara ('Apsara dance').";
const folkDance = "Created in the 20th century are folk dances that emphasize that various cultural traditions and ethnic groups of Cambodia. Cambodian folk dances are usually more fast-paced than classical dances. The movements and gestures are not as stylized as classical dance. Folk dancers wear clothes of the people they are portraying such as Chams, hill tribes, farmers, and peasants. Some folk dances are about love or folktales. Most of the music of folk dances is played by a mahori orchestra.";
const SocialDance = "Social dances commonly danced at social gatherings in Cambodia include the romvong, rom kbach, saravann, chok krapeus and lam leav. Other social dances from around the world have influenced Cambodian social culture, including the cha-cha, the bolero, and the Madison. Such dances are often performed at Cambodian banquet parties.";
const theatreofCambodia="Theatre of Cambodia known as Lakhon (Khmer: ល្ខោន) is composed of many different genres. There are three main categories: classical, folk, and modern. Many forms of theatre in Cambodia incorporates dance movement into performances and are referred to as dance dramas.";
const lakhonPreahReachTrop ="Lakhon Preah Reach Trop (Khmer: ល្ខោនព្រះរាជទ្រព្យ, also known as the Royal Ballet of Cambodia) is the main form of classical dance drama performed in Cambodia. It is also referred to as Lakhon luong and Lakhon Kbach Boran Khmer in Cambodia. This dance drama is the most refined of all theatre in Cambodia and was particularly patronized by royalty. It is heavily stylized with gestures and postures meant to entrance the viewer.";
const lakhonKhol = "Lakhon Khol (Khmer: ល្ខោនខោល, Masked Drama Dance) is a masked dance drama featuring male performers. The repertoire consists solely of material from Reamker. The choreography is styled similarly to the Royal Ballet of Cambodia although not as refined and is performed along to narrators and a pinpeat ensemble.";
const lakhonPolSrey ="Lakhon Pol Srey (Khmer: ល្ខោនពោលស្រី, Female Narrative Theatre) is a dance drama akin to the lakhon khol; the performers being female however. Both forms combine classical theatre and dance and are accompanied by the traditional pin peat orchestra. Unlike Lakhon Khol, which use a separate group of narrators, lakhon pol srey dancers take turns narrating while other members continue to dance. The dancers often lift their masks and narrate directly to the audience. It is believed to have originated from the Kingdom of Oudong between 1618-1628 during the reign of King Chey Chettha II. In 1878, Ms. Chinh, a great art teacher from Koh Oknheatey, came to teach Lakhon Pol Srey in Wat Keansvay Krao. Today, one of her students, a 70-year-old woman, Ms. Chea Samut, has taken a lead role in reviving lakhaon poul srei and currently teaches this drama form to students at Wat Keansvay Krao, after having disappeared for more than 40 years.";
const lakhonBerkBat ="Lakhon Berk Bat is a lost theatre form in Cambodian Court. It is believed to have originated in the Post-Angkor period. Some older Royal Ballet dancers also recalled hearing that it was created in the late Angkor period, but little is known as to why it was discontinued. Evidence reveals that the drama was re-instituted during the reign of Oudong city by King Norodom in the late 1950s. The form disappeared again in the late 1970s during the time of the Khmer Rouge regime. It is assumed that lakhon berk bat was only performed in the presence of royal or noble families due to the dancers elaborate and expensive costumes and jewelry. As the art form emphasized beauty, character and technique, performers were expected to be not only beautiful, but to be able to act, sing, and speak well. The ability to sing unaccompanied was especially prized.";
const lakhonNangSbek ="Lakhon Nang Sbek (Khmer: ល្ខោនណាំងស្បែក, Shadow Puppet Theatre) refers to Khmer shadow theatre.";
const yike ="Yike is dance drama with strong influences from Cham and Malay culture. It utilizes a style of singing reminiscent of the Islamic traditions of the Cham and Malay people. It incorporates basic dance movements with the hands swaying back and forth, although not as stylized as classic forms. The music consists of rebana drums and other Khmer instruments such as the tro."; 
const lakhonBassacorBasak = "Lakhon bassac or basak is one of the most popular folk theatre in Cambodia. It takes its name from the districts adjoining in the Bassac river in the former Cambodian province of Preah Trapeang, now known as Trà Vinh Province and part of Southern Vietnam. In the day of French rule, the troupes freely moved between Cambodia and Southern Vietnam, for both areas is the part of French Indochina. It is reminiscent of Vietnamese opera with the male character costumes styled after Vietnamese opera costumes, although the female characters wears traditional Cambodian costumes. Lakhon bassac is the only theatre form familiar with in which Indian based theatrical elements and Sinic based theatrical elements are mixed in almost equal amount.";
const lakhonPhlengKar = "Lakhon phleng kar (Khmer: ល្ខោនភ្លេងការ, lit., 'wedding music theatre') is a drama performed accompanied by traditional wedding music. This theatre form had travel from the court into the regular people's favourite. It notable used in Cambodia for the rich family until Lovek era after the strongly Javanese Influenced both on Music and wedding dress. The drama, like the music, is believed to have appeared as early as the 1st century during the wedding ceremony of Preah Thong and Neang Neak.";

export {
    art,
    architecture,
    sculpture ,
    destruction ,
    music ,
    classical,
    rockAndPop,
    literatuerOfCambodia,
    danceInCambodia,
    classicalDance,
    folkDance,
    SocialDance,
    theatreofCambodia,
    lakhonPreahReachTrop,
    lakhonKhol,
    lakhonPolSrey,
    lakhonBerkBat,
    lakhonNangSbek,
    yike,
    lakhonBassacorBasak,
    lakhonPhlengKar,
};