const dataMember = [
    {
        id:1,
        profile: "/images/sleanghak.jpg",
        name: "Leanghak SEIREY",
        job_title: "Web Front-end Developer",
        linkedin: "https://www.linkedin.com/in/leanghak-seirey-41901a236/",
        facebook: "https://www.facebook.com/sleanghak",
        telegram: "https://t.me/SEIREY_Leanghak",
    },
    {
        id:2,
        profile: "/images/vit_phnumvann.jpg",
        name: "Vit Phnumvann",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
    {
        id:3,
        profile: "/images/van_virot.jpg",
        name: "Van Virot",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
    {
        id:4,
        profile: "/images/himim_nheantusanak.jpg",
        name: "Himim Nheantusanak",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
    {
        id:5,
        profile: "/images/menghong_taihor.JPG",
        name: "Menghong Taihor",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
    {
        id:6,
        profile: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhf0bFAt6BMAzWUEXnJEsxJNG5bQT27ZiyveWOX_UT4DXtJR1vZaFA4IOOGMTV81S2oNw7BBkKkUD_J4uHWJMzkE8yvlikGbPp4Zl_zl1xRnbZmdf92IOATPxO7TVaR8X9ePW4dPaos4XreAQCwmR7HstDrm671ZOIZV-j9fsdis-fgnNgQiz-2VbOhaZw/s1600/images%20%281%29.jpg",
        name: "CHUOK KIMSENG",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
    {
        id:7,
        profile: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhf0bFAt6BMAzWUEXnJEsxJNG5bQT27ZiyveWOX_UT4DXtJR1vZaFA4IOOGMTV81S2oNw7BBkKkUD_J4uHWJMzkE8yvlikGbPp4Zl_zl1xRnbZmdf92IOATPxO7TVaR8X9ePW4dPaos4XreAQCwmR7HstDrm671ZOIZV-j9fsdis-fgnNgQiz-2VbOhaZw/s1600/images%20%281%29.jpg",
        name: "NANG LENGKEA",
        job_title: "Web Developer",
        linkedin: "#",
        facebook: "#",
        telegram: "#",
    },
];

export {
    dataMember,
};